### ISSUE TITLE
Leaks Hardcore map

### ISSUE THREAD

**Issue by Infinity585** [RustyMoose/Moose.Maps#1]
Loading custom map from https://github.com/RustyMoose/Moose.Maps/raw/main/Maps/4250/proceduralmap_4250_176597483.map
Shows in consol when joining RustyMoose Hardcore so it leaks the current hardcore map not sure if you guys know or if there's anything you can do about it. I also confirmed the map is the same via RustEdit and seeing the map was the same and spawns were the same.

**Comment by AdrianIsBored** [comment]
More of a facepunch issue

**Comment by tyronebiggnutz** [comment]
Sorry just noticed this. What Adrian said is correct, Facepunch would have to fix this.  However I rename the map file to match a different, random map so no one would be able to find the exact map on rustmaps.  There's other ways to get it but hopefully by doing this people think they got the right one :)
